#!/bin/zsh

# checks whether there is already an instance of $1
run () {
    if ! pgrep -f "$1" ;
    then
        "$@"&
    fi
}

# setting polish keyboard map
setxkbmap pl

# picom
run picom &

# nitrogen
run nitrogen --restore

# run the weather script, so the widget is up-to-date
$HOME/.config/eww/bars/main/scripts/weather --data

# widgets for the second screen run only if there is one
screens=$(xrandr -q | grep -w "connected" | wc -l)
if [[ $screens -gt 1 ]]
then
  # starting eww widgets (two screens)
  $HOME/.local/wm/eww/target/release/eww -c $HOME/.config/eww/bars/main open-many main-wspaces clock-date weather sysinfo &&
  $HOME/.local/wm/eww/target/release/eww -c $HOME/.config/eww/bars/secondary open-many auxiliary-wspaces clock-date
else
  # starting eww widgets (single screen)
  $HOME/.local/wm/eww/target/release/eww -c $HOME/.config/eww/bars/main open-many main-wspaces clock-date weather sysinfo
fi
